<?xml version="1.0" encoding="utf-8"?><Database Name="SQL2008R2_932096_meetings" Class="meetingDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql2k804.discountasp.net;Initial Catalog=SQL2008R2_932096_meetings;Persist Security Info=True;User ID=SQL2008R2_932096_meetings_user" SettingsObjectName="ResponsiveMeetingSearch.Data.Properties.Settings" SettingsPropertyName="SQL2008R2_932096_meetingsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Meeting" Member="Meetings">
    <Type Name="Meeting">
      <Column Name="ID" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(15,12) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(15,12) NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeOfMeeting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.RadiusSearch" Method="RadiusSearch">
    <Parameter Name="longitude" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="latitude" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="radius" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="DayOfWeek" Parameter="dayOfWeek" Type="System.Int32" DbType="Int" />
    <ElementType Name="RadiusSearchResult">
      <Column Name="ID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(15,12) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(15,12) NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeOfMeeting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>