//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponsiveMeetingSearch.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql2k804.discountasp.net;Initial Catalog=SQL2008R2_932096_meetings;Pe" +
            "rsist Security Info=True;User ID=SQL2008R2_932096_meetings_user")]
        public string SQL2008R2_932096_meetingsConnectionString {
            get {
                return ((string)(this["SQL2008R2_932096_meetingsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sql2k804.discountasp.net;Initial Catalog=SQL2008R2_932096_meetings;Pe" +
            "rsist Security Info=True;User ID=SQL2008R2_932096_meetings_user;Password=1234")]
        public string SQL2008R2_932096_meetingsConnectionString1 {
            get {
                return ((string)(this["SQL2008R2_932096_meetingsConnectionString1"]));
            }
        }
    }
}
